import { Character } from "./character";

export const CHARACTERS: Character[] = [
    { id: 1, file: "tile000.png", name: "Sissel" },
    //{ id: 1,file: "tile035.png", name: "Sissel?" },
    { id: 2, file: "tile001.png", name: "Lynne" },
    { id: 3, file: "tile002.png", name: "Ray" },
    { id: 4, file: "tile003.png", name: "Jeego" },
    { id: 5, file: "tile004.png", name: "Commander Sith" },
    { id: 6, file: "tile005.png", name: "Masked Muscleman" },
    { id: 7, file: "tile006.png", name: "Tengo" },
    { id: 8, file: "tile007.png", name: "Kamila" },
    { id: 9, file: "tile008.png", name: "Missle" },
    { id: 10,file: "tile009.png", name: "Emma" },
    { id: 11,file: "tile010.png", name: "Amelie" },
    { id: 12,file: "tile011.png", name: "Justice Minister" },
    { id: 13,file: "tile012.png", name: "Detective Mccaw" },
    { id: 14,file: "tile013.png", name: "The Blue Detective" },
    { id: 15,file: "tile014.png", name: "Odd Blue Doctor" },
    { id: 16,file: "tile015.png", name: "Inspector Cabanela" },
    { id: 17,file: "tile016.png", name: "Detective Rindge" },
    { id: 18,file: "tile017.png", name: "Guardian of the Park" },
    { id: 19,file: "tile018.png", name: "Pigeon Man" },
    { id: 20,file: "tile019.png", name: "Chicken Kitchen Cook" },
    { id: 21,file: "tile020.png", name: "Typical Cop" },
    { id: 22,file: "tile021.png", name: "Officer Bailey" },
    { id: 23,file: "tile022.png", name: "Rock Jailbird" },
    { id: 24,file: "tile023.png", name: "Curry-loving Jailbird" },
    { id: 25,file: "tile024.png", name: "Prisoner D99" },
    //{ id: 25,file: "tile025.png", name: "Detective Jowd" }, //With Green Jacket
    { id: 26,file: "tile026.png", name: "SIU Chief" },
    { id: 27,file: "tile027.png", name: "Memry " },
    { id: 28,file: "tile028.png", name: "Dandy" },
    { id: 29,file: "tile029.png", name: "Beauty" },
    { id: 30,file: "tile030.png", name: "Bartender" },
    { id: 31,file: "tile031.png", name: "???" },
    //{ id: 32,file: "tile032.png", name: "Alma" },
    { id: 32,file: "tile033.png", name: "Minor Crew Hand" },
    { id: 33,file: "tile034.png", name: "Guard" },
];